### PR TITLE
SSH key access

### PR DESCRIPTION
**Pull request by manojsonu7**
added user ssh key as per instructions

### CODE REVIEW

**Comment by anseifert** [comment]
@manojsonu7 - are you part of red hat?  you dont need to necessarily add yourself to both red hat and exxon groups in the bastion unless you need to.  I tried to look you up but got nowhere :).  

feel free to email me if you have questions

**Comment by manojsonu7** [comment]
> @manojsonu7 - are you part of red hat? you dont need to necessarily add yourself to both red hat and exxon groups in the bastion unless you need to. I tried to look you up but got nowhere :).
> 
> feel free to email me if you have questions

No, I am not part of red hat. I would need ssh access to the edge-lab-ansible. Do I have to remove myself from the exxon groups?

**Comment by anseifert** [comment]
which group or customer base are you with?

**Comment by manojsonu7** [comment]
> which group or customer base are you with?

@jarcher can you please help @anseifert?

**Pull request merged**
